import {ConvexClientProvider} from "@/components/convex-client-provider";
import {ConvexAuthNextjsServerProvider} from "@convex-dev/auth/nextjs/server";
import type {Metadata} from "next";
import {Inter} from "next/font/google";

import "./globals.css";
import React from "react";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Loom clone",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="en">
            <body className={inter.className}>
            <ConvexClientProvider>
                {children}
            </ConvexClientProvider>
            </body>
            </html>
        </ConvexAuthNextjsServerProvider>
    );
}
